# Resolve the path to the Ensembles.jl source tree (three levels up from
# the R-package source) and the parity fixtures generated by
# `Rscript test/reference/generate.R`.

ENS_REPO_ROOT <- normalizePath(
  file.path(testthat::test_path(), "..", "..", "..", ".."),
  mustWork = TRUE
)
ENS_REF_DIR <- file.path(ENS_REPO_ROOT, "test", "reference")
options(ensembles.jl_path = ENS_REPO_ROOT)
